/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3 */

#include "cert.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cert_RawNebulaCertificate, cert_RawNebulaCertificate, AUTO)


PB_BIND(cert_RawNebulaCertificateDetails, cert_RawNebulaCertificateDetails, AUTO)



